//
//  TestTagsConstants.swift
//  mobileSDK.UI
//
//  Created by Artem Serebrennikov on 13.04.2023.
//

extension String {
    //Common
    static let TEST_TAG_PREFIX_SAVE_CARD = "SAVE_CARD_"
    static let TEST_TAG_PREFIX_NEW_CARD = "NEW_CARD_"
    static let TEST_TAG_PREFIX_GOOGLE_PAY = "GOOGLE_PAY_"
    static let TEST_TAG_PREFIX_APS = "APS_"

    static let TEST_TAG_PREFIX_TOKENIZE = "TOKENIZE_"

    static let TEST_TAG_POSTFIX_CUSTOMER_FIELD = "_CUSTOMER_FIELD"
    static let TEST_TAG_POSTFIX_LINK = "_LINK"
    static let TEST_TAG_POSTFIX_ICON = "_ICON"
    static let TEST_TAG_POSTFIX_DEFAULT = "_DEFAULT"
    static let TEST_TAG_POSTFIX_LOCAL = "_LOCAL"
    static let TEST_TAG_POSTFIX_REMOTE = "_REMOTE"

    static let TEST_TAG_POSTFIX_TEXT = "_TEXT"
    static let TEST_TAG_POSTFIX_BUTTON = "_BUTTON"
    static let TEST_TAG_POSTFIX_TEXT_FIELD = "_TEXT_FIELD"

    static let TEST_TAG_POSTFIX_LABEL = "_LABEL"
    static let TEST_TAG_POSTFIX_VALUE = "_VALUE"

    static let TEST_TAG_DARK_THEME = "DARK"
    static let TEST_TAG_LIGHT_THEME = "LIGHT"
    static let TEST_TAG_FREE_SPACE_CLOSE_PAYMENT_BUTTON = "FREE_SPACE_CLOSE_PAYMENT\(Self.TEST_TAG_POSTFIX_BUTTON)"

    static let TEST_TAG_FOOTER_IMAGE = "FOOTER_IMAGE"
    static let TEST_TAG_LOGO_IMAGE = "LOGO_IMAGE"

    //Text
    static let TEST_TAG_SCREEN_TITLE_TEXT = "SCREEN_TITLE\(Self.TEST_TAG_POSTFIX_TEXT)"
    static let TEST_TAG_FOOTER_LABEL_TEXT = "FOOTER\(Self.TEST_TAG_POSTFIX_LABEL)\(Self.TEST_TAG_POSTFIX_TEXT)"

    static let TEST_TAG_COINS_VALUE_TEXT = "COINS\(Self.TEST_TAG_POSTFIX_VALUE)\(Self.TEST_TAG_POSTFIX_TEXT)"
    static let TEST_TAG_CURRENCY_VALUE_TEXT = "CURRENCY\(Self.TEST_TAG_POSTFIX_VALUE)\(Self.TEST_TAG_POSTFIX_TEXT)"
    static let TEST_TAG_TOTAL_PRICE_TITLE_TEXT = "TOTAL_PRICE_TITLE\(Self.TEST_TAG_POSTFIX_TEXT)"
    static let TEST_TAG_VAT_INCLUDED_LABEL_TEXT = "VAT_INCLUDED\(Self.TEST_TAG_POSTFIX_LABEL)\(Self.TEST_TAG_POSTFIX_TEXT)"
    static let TEST_TAG_PAYMENT_ID_LABEL_TEXT = "PAYMENT_ID\(Self.TEST_TAG_POSTFIX_LABEL)\(Self.TEST_TAG_POSTFIX_TEXT)"
    static let TEST_TAG_PAYMENT_ID_VALUE_TEXT = "PAYMENT_ID\(Self.TEST_TAG_POSTFIX_VALUE)\(Self.TEST_TAG_POSTFIX_TEXT)"
    static let TEST_TAG_PAYMENT_DESCRIPTION_LABEL_TEXT = "PAYMENT_DESCRIPTION\(Self.TEST_TAG_POSTFIX_LABEL)\(Self.TEST_TAG_POSTFIX_TEXT)"
    static let TEST_TAG_PAYMENT_DESCRIPTION_VALUE_TEXT = "PAYMENT_DESCRIPTION\(Self.TEST_TAG_POSTFIX_VALUE)\(Self.TEST_TAG_POSTFIX_TEXT)"
    static let TEST_TAG_ADDRESS_LABEL_TEXT = "ADDRESS\(Self.TEST_TAG_POSTFIX_LABEL)\(Self.TEST_TAG_POSTFIX_TEXT)"
    static let TEST_TAG_ADDRESS_VALUE_TEXT = "ADDRESS\(Self.TEST_TAG_POSTFIX_VALUE)\(Self.TEST_TAG_POSTFIX_TEXT)"

    static let TEST_TAG_PAYMENT_METHOD_ITEM_TITLE_TEXT = "PAYMENT_METHOD_ITEM_TITLE\(Self.TEST_TAG_POSTFIX_TEXT)"
    static let TEST_TAG_PAYMENT_METHOD_ITEM_SECTION = "PAYMENT_METHOD_ITEM_SECTION"
    static let TEST_TAG_APS_PAYMENT_DISCLAIMER_TEXT = "\(Self.TEST_TAG_PREFIX_APS)PAYMENT_DISCLAIMER\(Self.TEST_TAG_POSTFIX_TEXT)"

    static let TEST_TAG_LOADING_TITLE_TEXT = "LOADING_TITLE\(Self.TEST_TAG_POSTFIX_TEXT)"
    static let TEST_TAG_LOADING_SUB_TITLE_TEXT = "LOADING_SUB_TITLE\(Self.TEST_TAG_POSTFIX_TEXT)"

    static let TEST_TAG_ADDITIONAL_DATA_DISCLAIMER_TEXT = "ADDITIONAL_DATA_DISCLAIMER\(Self.TEST_TAG_POSTFIX_TEXT)"

    static let TEST_TAG_BUTTON_CURRENCY_TEXT = "BUTTON_CURRENCY\(Self.TEST_TAG_POSTFIX_TEXT)"
    static let TEST_TAG_BUTTON_AMOUNT_TEXT = "BUTTON_AMOUNT\(Self.TEST_TAG_POSTFIX_TEXT)"
    static let TEST_TAG_BUTTON_LABEL_TEXT = "BUTTON_LABEL\(Self.TEST_TAG_POSTFIX_TEXT)"

    //Text fields
    static let TEST_TAG_CVV_TEXT_FIELD = "CVV\(Self.TEST_TAG_POSTFIX_TEXT_FIELD)"
    static let TEST_TAG_EXPIRY_TEXT_FIELD = "EXPIRY\(Self.TEST_TAG_POSTFIX_TEXT_FIELD)"
    static let TEST_TAG_CARDHOLDER_TEXT_FIELD = "CARDHOLDER\(Self.TEST_TAG_POSTFIX_TEXT_FIELD)"
    static let TEST_TAG_PAN_TEXT_FIELD = "PAN\(Self.TEST_TAG_POSTFIX_TEXT_FIELD)"

    //Buttons
    static let TEST_TAG_SCREEN_CLOSE_BUTTON = "SCREEN_CLOSE\(Self.TEST_TAG_POSTFIX_BUTTON)"
    static let TEST_TAG_SCREEN_BACK_BUTTON = "SCREEN_BACK\(Self.TEST_TAG_POSTFIX_BUTTON)"
    static let TEST_TAG_PAYMENT_DETAILS_BUTTON = "PAYMENT_DETAILS\(Self.TEST_TAG_POSTFIX_BUTTON)"
    static let TEST_TAG_SAVE_BUTTON = "SAVE\(Self.TEST_TAG_POSTFIX_BUTTON)"
    static let TEST_TAG_AUTHORIZE_BUTTON = "AUTHORIZE\(Self.TEST_TAG_POSTFIX_BUTTON)"
    static let TEST_TAG_PAY_BUTTON = "PAY\(Self.TEST_TAG_POSTFIX_BUTTON)"
    static let TEST_TAG_PROCEED_BUTTON = "PROCEED\(Self.TEST_TAG_POSTFIX_BUTTON)"
    static let TEST_TAG_CONFIRMATION_BUTTON = "CONFIRMATION\(Self.TEST_TAG_POSTFIX_BUTTON)"
    static let TEST_TAG_CLOSE_BUTTON = "CLOSE\(Self.TEST_TAG_POSTFIX_BUTTON)"
    static let TEST_TAG_TRY_AGAIN_BUTTON = "TRY_AGAIN\(Self.TEST_TAG_POSTFIX_BUTTON)"
    static let TEST_TAG_DONE_BUTTON = "DONE\(Self.TEST_TAG_POSTFIX_BUTTON)"
    static let TEST_TAG_GOOGLE_PAY_BUTTON = "GOOGLE_PAY\(Self.TEST_TAG_POSTFIX_BUTTON)"
    static let TEST_TAG_CARD_SCANNING_BUTTON = "CARD_SCANNING\(Self.TEST_TAG_POSTFIX_BUTTON)"
    static let TEST_TAG_DELETE_CARD_BUTTON = "DELETE_CARD\(Self.TEST_TAG_POSTFIX_BUTTON)"
    static let TEST_TAG_CVV_INFO_BUTTON = "CVV_INFO\(Self.TEST_TAG_POSTFIX_BUTTON)"
    static let TEST_TAG_CANCEL_PAYMENT_BUTTON = "CANCEL_PAYMENT\(Self.TEST_TAG_POSTFIX_BUTTON)"
}
