# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!
workspace 'TestClientUI.xcworkspace'
project 'TestClientUI'
project '../mobileSDK.Facade/mobileSDK.Facade.xcodeproj'

#TestClient

TestClientTargets = ["TestClient", "TestClient_1D3", "TestClient_JetPay"]

for targetName in TestClientTargets
  target targetName do
    project 'TestClientUI'
    pod 'EFColorPicker'
    pod 'SnapKit'
    pod 'AppCenter'
    pod 'Reachability'
  end
end

#mSDK iOS

mSDKTargets = ["ecommpaySDK"]
#mSDKTargets = ["ecommpaySDK", "ODTSDK", "jetpayhostsSDK"]
#mSDKTargetsDev = mSDKTargets.collect { |x| x + "-Dev" }
#mSDKTargets += mSDKTargetsDev
for targetName in mSDKTargets
  target targetName do
    project '../mobileSDK.Facade/mobileSDK.Facade.xcodeproj'
    pod 'MsdkCore'
  end
end
=begin
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64 arm64e armv7 armv7s"
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
      config.build_settings['ENABLE_BITCODE'] = 'YES'
    end
  end
end
=end
