# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IntegrationExampleSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IntegrationExampleSwift
  pod 'EcommpaySDK_UI', '3.0.0'
end
