name: SDK CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer

      - name: Bundle install
        run: |
          brew install grep
          bundle install
      
      - name: Cache SPM packages
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            .build
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      
      - name: Validate
        run: |
          bundle exec fastlane validate
      
