name: SDK CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Bundle install
        run: |
          brew install grep
          bundle install
      
      - name: Validate
        run: |
          bundle exec fastlane validate
      
